# Final Exam
---

### Notes:


- This exam is open book/open browser. That means you are allowed to use any resources to answer the questions, except communication with any other person.


- Once finished you should upload your exam to your personal submission folder in the TUBS-Cloud, that we have assigned to you. If you haven't been assigned to one, tell us now!


- The first part consists of 10 multiple choice questions, each increasing your final score by 5 points when answered corretly.


- More details on the theory part and programming part are given below. 


- Please read the instructions carefully.


- Good Luck!

# Part I: Machine Learning theory (50/100 pts.)
Please answer the multiple choice questions below. For each question, there is exactly ***ONE*** correct answer. Selecting multiple answers or the wrong answer results in 0 points for that question. Each question will have 4 different answer choices, numbered from 1-4. After each question, there will be a cell that you can use to place your answer. You just need to enter ***the number of the answer*** to that question, e.g. a number between 1-4.

## Question 1 (5pts.)

A ***regression model***(e.g. linear regression) expects an input of type $\mathbf x \ \epsilon \ \mathbb R^{d}$, where $\mathbf x$ can have multiple dimensions/features(e.g. d=4 features/columns).
What dimensionality and range of possible values does a label in a regression dataset have ?

1. $y \ \epsilon \ \{0, 1\}$, so y is either a scalar number equal to "1", or equal to "0" which represents one of two classes.


2. $y \ \epsilon \ \mathbb R$, so y can represent any scalar number on the real line.


3. $y \ == \ \mathbf x$, so y has the same dimensionality and value as $\mathbf x$.


4. $y \ \epsilon \ \emptyset$, so there is no y-labels in a regresion task.

In [1]:
# 2

## Question 2 (5pts.)

A ***binary classification model***(e.g. binary nearest centroid classifier) expects an input of type $\mathbf x \ \epsilon \ \mathbb R^{d}$, where $\mathbf x$ can have multiple dimensions/features(e.g. d=4 features/columns).
Select the type of a label "$y$" in a typical classification task:

1. $y \ \epsilon \ \{0, 1\}$, so y is either a scalar number equal to "1", or equal to "0" which represents one of two classes.


2. $y \ \epsilon \ \mathbb R$, so y can represent any scalar number on the real line.


3. $y \ == \ \mathbf x$, so y has the same dimensionality and value as $\mathbf x$.


4. $y \ \epsilon \ \emptyset$, so there is no y-labels in a classification task.

In [5]:
# 1

## Question 3 (5pts.)

A ***clustering model***(e.g. k-neigherst neighbor clustering) expects an input of type $\mathbf x \ \epsilon \mathbb \ R^{d}$, where $\mathbf x$ can have multiple dimensions/features(e.g. d=4 features/columns).
Select the type of a label "$y$" in a typical clustering task:

1. $y \ \epsilon \ \{0, 1\}$, so y is either a scalar number equal to "1", or equal to "0", which represents one of two classes.


2. $y \ \epsilon \ \mathbb R$, so y can represent any scalar number on the real line.


3. $y \ \epsilon \ \mathbf x_{input}$, so y has the same dimensionality and value as $\mathbf x$.


4. $y \ \epsilon \ \emptyset$, so there is no y-label in a clustering task.

In [2]:
# 4

## Question 4 (5pts.)

Which of these statements about the loss function is true ? 

1. The loss function is a way of measuring the performance of our machine learning model, which is used to optimize it.


2. The loss function and the error function are 2 separate things.


3. There exists 1 loss function that is used by every single machine learning algorithm.


4. The loss function is independent of our training data, which means that we don't need our training data to compute the loss of our machine learning model.

In [3]:
# 1

## Question 5 (5pts.)

Which of these statements about the learning rate $\alpha$ is true ? 

1. A large learning rate might result in never reaching the minimum of a loss function because our steps towards the minimum get too small to actually reach it. 


2. A small learning rate might result in "overshooting" the minimum of a loss function because we might "overshoot" the minimum.


3. The learning rate is the step size that our gradient descent algorithm takes towards the direction of greatest decrease of our loss function, with respect to our model parameters.


4. There learning rate has no impact on the optimization process of our loss function.

In [21]:
# 3

## Question 6 (5pts.)

A confusion matrix let's us compute a variety of metrics that can be used to measure the performance of our trained classification model. 
It usually consists of 4 fields, namely:

- True positives  / TP: The number of points that our model has predicted to be from class "1"(sometimes referred to as "positive" class), while their actual label was class "1".


- False positives / FP: The number of points that our model has predicted to be from class "1", while their actual label was class "0"(sometimes referred to as "negative class").


- False negatives / FN: The number of points that our model has predicted to be from class "0", while their actual label was class "1".


- True negatives  / TN: The number of points that our model has predicted to be from class "0", while their actual label was class "0".

How is the accuracy computed, when given the elements of our confusion matrix ? 

### NOTE: "Total" refers to the total amount of points of the whole dataset(training set or test set).

1. $Accuracy = \frac{TP+TN}{Total}$


2. $Accuracy = \frac{TP}{TP+FP}$


3. $Accuracy = \frac{TP}{TP+FN}$


4. $Accuracy = \frac{TP + FP + FN + TN}{Total}$

In [4]:
# 1

## Question 7 (5pts.)

Which of the following classification algorithms uses the distance between a new point x and the class means of multiple classes, as a decision rule for classification ?

1. Binary Logisitc Regression classifier


2. Binary K-nearest centroid classifier


3. Convolutional Neural Network


4. Linear Regression

In [47]:
# 2

## Question 8 (5pts.)

When preparing the dataset for our learning algorithm, which of these steps does ***not*** help to achieve a better training process, in terms of efficiency, robustness, performance etc.


1. Standardizing our features/columns.


2. Dropping features that don't correlate with our label while keeping the ones that do correlate with the labels.


3. Dropping all data points that belong to a certain label together with their labels. So at the end our dataset consists of only points from  a single class that we use for training.


4. Training a machine learning model on different sets of hyperparameters(e.g. learning rates) and chossing the set that increases the test performance of our model.

In [24]:
# 3

## Question 9 (5pts.)

When training a machine learning model, we usually do a training and test set split. What do we use the training and test set for ?

1. We use both the training set and the test set to train our model, and evaluate it's generalization performance on the accuracy of the concatenation of both data sets.


2. We use the training set to train our model and the test set to estimate it's generalization performance. That is, it's prediction accuracy on unseen data points.


3. We use the training and test split only to safe up computational time.


4. We use the test set to train our model and the training set to estimate it's generalization performance. That is, it's prediction accuracy on unseen data points.

In [6]:
# 2

## Question 10 (5pts.)

Which of these statements about convex funtions is true ? 

1. Optimizing a convex function with respect to a certain variable(e.g. some weight variable w), will result in a ***local*** optimum.


2. Convex functions are not differentiable and thus not optimizable.


3. Optimizing a convex function with respect to a certain variable(e.g. some weight variable w), will result in a ***global*** optimum.


4. There is no single loss/error function used in machine learning model that is a convex function.

In [48]:
# 1

# Part II: Python programming exercises (50/100 pts.)
For the programming exercises, please follow the following:
- follow the instructions for each exercise
- use the provided blocks to write your code, and do not delete any other code lines. 
- you can add cells for testing, but we will only evaluate what is in the block!
- it is not necessary, but you may add comments to your code, explaining what your were thinking and trying to do. If the solution is not correct, we still can give you points based on your ideas!
- do not hesistate to ask if something is not clear or you need help :)

## Exercise 1: Pandas(10 pts.) 

In [8]:
# run this to import the modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
%matplotlib inline

### 1.1 Parse the dataset population.csv into a pandas DataFrame and clean (5 pts.)

Complete the function `getData(path)`, which reads the file specified in the `path` input. The function should return a pandas `DataFrame`, containing the data in _population.csv_. The dataset holds data from the population of Barcelona over multiple years. For the following questions, we want to only use data from the year 2017. Therefore clean the data accordingly.

In [42]:
def getData(path):
    
    data = pd.read_csv(path ,header = 0)
    data = data[data.iloc[:,0] == 2017]
    
    return data

In [43]:
data = getData('population.csv')

In [46]:
data.head()

Year  District.Code District.Name  Neighborhood.Code  \
0  2017              1  Ciutat Vella                  1   
1  2017              1  Ciutat Vella                  2   
2  2017              1  Ciutat Vella                  3   
3  2017              1  Ciutat Vella                  4   
4  2017              2      Eixample                  5   

                       Neighborhood.Name Gender  Age  Population  
0                               el Raval   Male  0-4         224  
1                         el Barri Gòtic   Male  0-4          50  
2                         la Barceloneta   Male  0-4          43  
3  Sant Pere, Santa Caterina i la Ribera   Male  0-4          95  
4                          el Fort Pienc   Male  0-4         124

### 1.2 Parse the dataset population.csv into a pandas DataFrame and clean (5 pts.)

Complete the function `getData(path)`, which reads the file specified in the `path` input. The function should return a pandas `DataFrame`, containing the data in _population.csv_. The dataset holds data from the population of Barcelona over multiple years. For the following questions, we want to only use data from the year 2017. Therefore clean the data accordingly.

In [ ]:
def getTotalPopulation(data):
    
    population = ### Your code here ###
    
    return population

In [ ]:
getTotalPopulation(data)

## Exercise 2.0 Preprocessing (10 pts.)
### a) - Scaling (5 pts.)
For this exercise, you are given three datasets ```X1,X2,X3```. 

The goal of this exercise is to 
 - normalize each of the ```X1,X2,X3```, by implementing the ```normalize``` function below and using it with an appropriate ```X_property```.

The ```X_property``` determines, whether the data is sparse, or has outliers or none of the two. From this you must derive which of the imported Scalers to use. If ```X_property``` is ```None```, use the ```sklearn.preprocessing.StandardScaler```.

To complete the ```normalize``` function, you should
 - create the right scaler object for each possible ```X_property```
 - create a pipeline object to which you add the scaler
 - fit the pipeline to your input data ```X```
 - return the transformed ```X```


**After having implemented the function, please CORRECT AND UNCOMMENT the given print statements to see if your function runs withouot errors on the given data arrays.**

In [69]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.pipeline import make_pipeline
import numpy as np

X_properties = [None, 'sparse', 'has_outliers']

# data is not sparse and has not got any outliers
X1 = np.array([[ 1., -1.,  2.],
     [ 2.,  3.,  2.5],
    [ 0.5,  1., -1.]])

# data is sparse
X2 = np.array([[ 1., 0.,  2.],
     [ 0.,  3.,  0.],
    [ 0.5,  0., 0.]])

# data has outliers
X3 = np.array([[ 100., -1.,  2.],
     [ 2.,  3.,  2.5],
    [ 0.5,  1., -1.]])

def normalize(X, X_property=None):
    if X_property not in [None, 'sparse', 'has_outliers']:
        raise NotImplementedError
    
    if X_property == None: 
        pipeLine = make_pipeline(StandardScaler()) #create pipeline with argument standard scaler 
        pipeLine.fit(X)#fit the standar scaler pipeline on the given X
        return pipeLine.transform(X) #transforms the dataset
    elif X_property == 'sparse':
        pipeLine = make_pipeline(RobustScaler())# in this case we use RobustScaler because of the data distribution
        pipeLine.fit(X)
        return pipeLine.transform(X) #transforms the dataset
    elif X_property == 'has_outliers':
        pipeLine = make_pipeline(MaxAbsScaler())# in this case we use MaxAbsScaler because the dataset includes outliers
        pipeLine.fit(X)
        return pipeLine.transform(X) #transforms the dataset
    pass
    #<<<YOUE CODE ENDS <<<

print(normalize(X1, None))
# todo replace 'REPLACE_THIS_WITH_CORRECT_VALUE' with correct value
print(normalize(X2, 'sparse'))
print(normalize(X3, 'has_outliers'))

[[-0.26726124 -1.22474487  0.53916387]
 [ 1.33630621  1.22474487  0.86266219]
 [-1.06904497  0.         -1.40182605]]
[[ 1.  0.  2.]
 [-1.  2.  0.]
 [ 0.  0.  0.]]
[[ 1.         -0.33333333  0.8       ]
 [ 0.02        1.          1.        ]
 [ 0.005       0.33333333 -0.4       ]]


### b) Imputation (5 pts.)
For this exercise, you are given the dataset ```X_nan```.


You should now extend your ```normalize``` function, such that it can replace ```np.nan``` values by the mean value of the corresponding column. For that the function should now **additionally**
 - create a simple imputer with the right arguments
 - add the imputer object to the pipeline
 - fit the pipeline to your input data ```X```
 - return the transformed ```X```
 
 
Note: You can copy the normalize function from above.


**After having implemented the function, please uncomment the last print statement in this cell, to see if your function runs withouot errors on the given data array.**


In [87]:
from sklearn.impute import SimpleImputer
import numpy as np
X_properties = [None, 'sparse', 'has_outliers']

# data has missing values
Xnan = np.array([[ 100., -1.,  np.nan],
     [ 2.,  3.,  np.nan],
    [ np.nan,  1., -1.]])

def normalize(X, X_property=None):
    if X_property not in X_properties:
        raise NotImplementedError
    
    #>>> YOUR CODE HERE >>>
    
    
    if X_property == None: 
        pipeLine = make_pipeline(SimpleImputer(missing_values=np.nan, strategy='mean'),StandardScaler()) #create pipeline with argument standard scaler 
        pipeLine.fit(X)#fit the standar scaler pipeline on the given X
        return pipeLine.transform(X) #transforms the dataset
    elif X_property == 'sparse':
        pipeLine = make_pipeline(SimpleImputer(missing_values=np.nan, strategy='mean'),RobustScaler())# in this case we use RobustScaler because of the data distribution
        pipeLine.fit(X)
        return pipeLine.transform(X) #transforms the dataset
    elif X_property == 'has_outliers':
        pipeLine = make_pipeline(SimpleImputer(missing_values=np.nan, strategy='mean'),MaxAbsScaler())# in this case we use MaxAbsScaler because the dataset includes outliers
        pipeLine.fit(X)
        return pipeLine.transform(X) #transforms the dataset
    pass
    #<<<YOUE CODE ENDS <<<

print(normalize(Xnan, None))

[[ 1.22474487 -1.22474487  0.        ]
 [-1.22474487  1.22474487  0.        ]
 [ 0.          0.          0.        ]]


## Exercise 2.1 Feature Selection (10 pts.)
### a) Removing redundant features (5 pts.)

You are given a labelled dataset ```X, y``` for a binary classification problem. 
It consists of 4 features, where 2 are redundant. The goal of this exercise is to remove the two redundant features using ```sklearn.feature_selection.SelectFromModel``` and ```sklearn.svm.LinearSVC``` with the 'l1'-penalty, as shown in the lecture. For this you should implement the function ```remove_redundant_features(X)``` as follows:
 - create a linear support vector classifier using the right values for 'penalty' and 'dual'
 - normalize the data using your function from above (if you implemented it, otherwise do not normalize the data) 
 - fit the SelectFromModel transformer
 - return a boolean mask where Features are masked out that should be removed


**After having implemented the function, please uncomment the last print statement in this cell, to see if your function runs withouot errors on the given data array.**


Hints: 
- remember to set the right values for penalty and dual in the LinearSVC
- using threshold='median' will make sure that SelectFromModel reduces the number of features to two.


In [118]:
from sklearn.datasets import make_classification
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

X, y = make_classification(n_samples=100, 
                           n_classes=2,
                           n_features=4,
                           n_informative=2,
                           n_redundant=2,
                           random_state=42)

def remove_redundant_features(X):
    #>>> YOUR CODE HERE >>>
    linearSVC = LinearSVC(penalty='l1', dual=False)
    normalize(X)
    selector = SelectFromModel(linearSVC, threshold='median')
    selector.fit(X,y)
    return X
    pass
    #<<< YOUE CODE ENDS <<<

mask = remove_redundant_features(X)
mask

#couldnt really understand the mask statement 


array([[-1.05383855, -1.02754411, -0.32929388,  0.82600732],
       [ 1.56931739,  1.306542  , -0.23938468, -0.3313761 ],
       [-0.35885569, -0.69102126, -1.22532865,  1.65214494],
       [-0.1368559 ,  0.46093758,  1.89691056, -2.2813861 ],
       [-0.04862909,  0.50230075,  1.77872961, -2.17105282],
       [ 2.30450019,  1.33970234, -2.24075406,  1.83991037],
       [-0.40925706,  0.32423734,  2.23245441, -2.58590856],
       [-0.7173148 , -0.88602706, -0.83311649,  1.31217492],
       [ 1.06173727,  1.05688647,  0.40238353, -0.91916686],
       [ 1.48052803,  1.28131775, -0.06692233, -0.50833095],
       [ 0.53479393,  0.21164583, -0.84389686,  0.82584805],
       [ 1.38991764,  1.22541983,  0.01066604, -0.56772453],
       [-1.79532002, -1.46361184,  0.37531604,  0.25415746],
       [-1.26898369, -0.68933585,  1.39175475, -1.20757158],
       [-1.56826626, -0.87306613,  1.65095783, -1.40735658],
       [-0.42795824, -0.72216846, -1.12868571,  1.56070438],
       [ 0.73644435,  0.

## Exercise 2.1 Feature Selection (10 pts.)
### b) Refitting using reduced set of features (5 pts.)
You are given the same labelled dataset ```X, y``` as in the previous exercise ```3a)```.

After having implemented ```remove_redundant_featuers``` function above, you should now

 - apply ```remove_redundant_featuers``` to ```X``` **and transform  ```X``` using the result** (Hint: check the shape of ```X```, and consider using the transpose .T)
 - create train and test split using a random seed
 - normalize the data using your function from above (if you implemented it, otherwise do not normalize the data) 
 - now fit a LinearSVC on the reduced and normalized dataset ```Xtrain``` and 
 - print the result of calling its score method on the test data.

In [104]:
from sklearn.datasets import make_classification
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=100, 
                           n_classes=2,
                           n_features=4,
                           n_informative=2,
                           n_redundant=2,
                           random_state=42)

#>>> YOUR CODE HERE >>>
#remove_redundant_features(X)
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42) #
normalize(X_train), normalize(X_test)
linearSVC_2 = linearSVC = LinearSVC()
linearSVC_2.fit(X_train, Y_train)
print(linearSVC_2.score(X_test, Y_test))


#     pass
#<<< YOUE CODE ENDS <<<

0.9


## Exercise 3. Hyperparameter Optimization (10 pt)

You are given the same labelled dataset ```X, y``` as before and should now train a ```sklearn.svm.SVC estimator```. For that, a parameter grid is given, from which you should pick the parameter combination, which performs best on the classification task, given a handicap we provide. The handicap is the restriction of the dataset to only 20 percent of the data, which is already implemented for you via the train_test_split.

Your task is to implement the ```report_best_params_w_score``` function by 
 - normalizing ```Xtrain``` using your function from task ```3.0 a)``` or an appropriate sklearn function
 - doing a GridSearch using the import GridSearchCV object over the parameter grid (i.e. by properly calling its ```.fit``` method
 - printing the best parameters obtained
 - returning the best_estimator (Hint: see GridSearchCV's corresponding attribute in the documentation)
 

Finally, you should use the returned estimator, to evaluate the test score, by calling its .score method.


In [136]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

def report_best_params_w_score():
    X, y = make_classification(n_samples=100, 
                           n_features=4,
                           n_informative=2,
                           n_redundant=2,
                           random_state=42)

    param_grid = {'C': [0.1,1.,10], 'kernel': ['rbf', 'linear']}
    Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, 
                                                    random_state=42, 
                                                    test_size=0.8)
    #>>> YOUR CODE HERE >>>
    normalize(Xtrain)
    mySVC = SVC()
    mySVC = GridSearchCV(mySVC,param_grid,cv=None, scoring=None,return_train_score=True)
    mySVC.fit(X_train,Y_train)
    print(mySVC.best_params_)
    mySVC = mySVC.best_estimator_
    return mySVC
    pass
    #<<< YOUE CODE ENDS <<<

report_best_params_w_score()    


{'C': 1.0, 'kernel': 'linear'}


SVC(kernel='linear')

## Exercise 4: Logistic Regression optimization: Applying Gradient Descent using Binary Cross Entropy Loss(10 pts.)

- Implement the gradient descent algorithm on the Logistic Regression model as discussed in the lecture.
- use 100 epochs(update steps)
- use learning rate alpha of 0.0001
- use the X dataset from below. Use the whole X and y arrays, no train test split needed here.
- don't change the weight parameter(w) initialization and don't change the random seed
- Use the "log_loss" function that gets imported below. It's the SkLearn implementation for the binary-cross entropy loss function.
- Use the "expit" function that gets imported below. It's the SciPy implementation for the sigmoid function.
- Plot the training loss over epochs

#### The formula for the gradient of the binary-cross entropy loss function:
- $\nabla_{\mathbf w^t} J(\mathbf w^t) = \frac{1}{N}\mathbf X^T(\sigma(\mathbf X \mathbf w^t)-\mathbf y)$
- Update rule Gradient Descent: $\mathbf{w}^t=\mathbf{w}^t-\alpha \nabla_{\mathbf w} J(\mathbf w^t)$

In [ ]:
from scipy.special import expit
from sklearn.metrics import log_loss 
from sklearn.datasets import load_breast_cancer

In [ ]:
X, Y = load_breast_cancer(return_X_y=True)
X = np.hstack([np.ones((X.shape[0], 1)), X])

In [ ]:
X.shape

In [ ]:
Y.shape

In [ ]:
n_epochs = 100
alpha = 0.0001

In [ ]:
np.random.seed(42)
w = np.random.rand(X.shape[1],1)

loss = []

for i in range(n_epochs):        
    # Compute the gradient

    ### Your code here ###
            
    # Apply the udpate step
    ### Your code here ###
            
    # store the loss in the loss array (optional)
    ### Your code here ###
    
# Plot the loss
plt.plot(loss);
plt.xlabel("Epochs")
plt.ylabel("Loss");